# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swiftgen Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swiftgen Practice
pod 'SwiftGen', '~> 6.0'
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
end
