# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMRxSwift
pod 'Moya/RxSwift', '~> 15.0'
pod 'Moya/RxSwift', '~> 15.0'
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'
pod 'SDWebImage', '~> 5.0'

end
