# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase Practice

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'SnapKit', '~> 5.0.0'
pod 'Then'

end
